---
kind: pipeline
name: linnea1.csc.fi

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host: linnea1.csc.fi
    key:
      from_secret: ssh_key_linnea1.csc.fi
    rm: true
    source:
    - "*"
    tar_exec: /usr/sfw/bin/gtar
    target:  /m1/voyager/usemarcon/rda_fin2swe
    username:
      from_secret: username_linnea1.csc.fi

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: linnea3.csc.fi

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host: linnea3.csc.fi
    key:
      from_secret: ssh_key_linnea3.csc.fi
    rm: true
    source:
    - "*"
    tar_exec: /usr/sfw/bin/gtar
    target:  /m1/voyager/usemarcon/rda_fin2swe
    username:
      from_secret: username_linnea3.csc.fi

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: armas.csc.fi

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host: armas.csc.fi
    key:
      from_secret: ssh_key_armas.csc.fi
    rm: true
    source:
    - "*"
    tar_exec: /usr/sfw/bin/gtar
    target:  /m1/voyager/usemarcon/rda_fin2swe
    username:
      from_secret: username_armas.csc.fi

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: libtest2.csc.fi

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host: libtest2.csc.fi
    key:
      from_secret: ssh_key_libtest2.csc.fi
    rm: true
    source:
    - "*"
    tar_exec: /usr/sfw/bin/gtar
    target:  /m1/voyager/usemarcon/rda_fin2swe
    username:
      from_secret: username_libtest2.csc.fi

trigger:
  branch:
  - test
  event:
  - push

---
kind: pipeline
name: replikointi-kk.lib.helsinki.fi

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host: replikointi-kk.lib.helsinki.fi
    key:
      from_secret: ssh_key_replikointi-kk.lib.helsinki.fi
    rm: true
    source:
    - "*"
    target:  /opt/usemarcon/rda_fin2swe
    username:
      from_secret: username_replikointi-kk.lib.helsinki.fi

trigger:
  branch:
  - master
  event:
  - push

...
