matrix:
  include:
  - HOST: replikointi-kk.lib.helsinki.fi
    USER: usemarcon
    DIRECTORY: /opt/usemarcon/rda_fin2swe
  - HOST: libtest2.csc.fi
    USER: voyager
    DIRECTORY: /m1/voyager/usemarcon/rda_fin2swe
#  - HOST: linnea1.csc.fi
#    USER: voyager
#    DIRECTORY: /m1/voyager/usemarcon/rda_fin2swe
#  - HOST: linnea3.csc.fi
#    USER: voyager
#    DIRECTORY: /m1/voyager/usemarcon/rda_fin2swe
#  - HOST: armas.csc.fi
#    USER: voyager
#    DIRECTORY: /m1/voyager/usemarcon/rda_fin2swe
pipeline:
  package:
    image: busybox:1
    commands:
    - tar -czf package.tar.gz *
  copy-package:
    image: quay.io/natlibfi/drone-plugin-scp
    host: ${HOST}
    username: ${USER}
    target: ${DIRECTORY}
    source: package.tar.gz
    rm: true
    secrets:
    - source: ssh_key_${HOST}_${USER}
      target: ssh_key
  extract-package:
    image: quay.io/natlibfi/drone-plugin-ssh
    host: ${HOST}
    username: ${USER}
    script:
    - tar -xf ${DIRECTORY}/package.tar.gz -C ${DIRECTORY}
    - rm ${DIRECTORY}/package.tar.gz
    secrets:
    - source: ssh_key_${HOST}_${USER}
      target: ssh_key
